name: WorldPluginManager
main: fr.P2W.wplmanager.WorldPluginManager
version: 2.0
softdepend: [ProtocolLib]
commands:
  displ:
    description: Disables a plugin in a specified world.
    usage: /displ <plugin> <world>
    permission: worldpluginmanager.displ
  enpl:
    description: Enables a plugin in a specified world.
    usage: /enpl <plugin> <world>
    permission: worldpluginmanager.enpl
  flags:
    description: Displays the status of plugins in a specified world.
    usage: /flags <world> [plugin]
    permission: worldpluginmanager.flags
  focus:
    description: Sets a plugin to be enabled only in a specified world.
    usage: /focus <plugin> <world>
    permission: worldpluginmanager.focus
permissions:
  worldpluginmanager.displ:
    description: Allows the use of the /displ command.
    default: op
  worldpluginmanager.enpl:
    description: Allows the use of the /enpl command.
    default: op
  worldpluginmanager.flags:
    description: Allows the use of the /flags command.
    default: op
  worldpluginmanager.focus:
    description: Allows the use of the /focus command.
    default: op
